owner: strike-cloud
git-repo: helm-charts
git-base-url: https://api.github.com/
git-upload-url: https://uploads.github.com/
charts-repo: https://strike-cloud.github.io/helm-charts/
index-path: index.yaml
skip-existing: false
generate-release-notes: true
latest-tag: true