## Reference: https://github.com/pascalgn/size-label-action
name: 'PR Labeling'

on: 
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4.3.0
        with:
          configuration-path: ".github/configs/labeler.yaml"
          repo-token: "${{ secrets.GH_TOKEN }}"
          sync-labels: true

  size-label:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.0
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"